config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#               home_index GET    /home/index(.:format)          home#index
#                chatrooms GET    /chatrooms(.:format)           chatrooms#index
#                          POST   /chatrooms(.:format)           chatrooms#create
#             new_chatroom GET    /chatrooms/new(.:format)       chatrooms#new
#            edit_chatroom GET    /chatrooms/:id/edit(.:format)  chatrooms#edit
#                 chatroom GET    /chatrooms/:id(.:format)       chatrooms#show
#                          PATCH  /chatrooms/:id(.:format)       chatrooms#update
#                          PUT    /chatrooms/:id(.:format)       chatrooms#update
#                          DELETE /chatrooms/:id(.:format)       chatrooms#destroy
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#            user_password PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
#                          POST   /users/password(.:format)      devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#        user_registration PATCH  /users(.:format)               devise/registrations#update
#                          PUT    /users(.:format)               devise/registrations#update
#                          DELETE /users(.:format)               devise/registrations#destroy
#                          POST   /users(.:format)               devise/registrations#create
#

Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :chatrooms do
    resource :chatroom_users
    resource :messages
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users
  has_many :messages
  has_many :users, through: :chatroom_users
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :chatroom_users
  has_many :messages
  has_many :chatrooms, through: :chatroom_users
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chatroom_users_controller.rb
class ChatroomUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom

  def create
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
    redirect_to @chatroom
  end

  def destroy
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).destroy_all
    redirect_to chatrooms_path
  end

  private
    def set_chatroom
      @chatroom = Chatroom.find(params[:chatroom_id])
    end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.all
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
    @messages = @chatroom.messages.order(created_at: :desc).limit(100)
    @chatroom_user = current_user.chatroom_users.find_by(chatroom_id: @chatroom_id)
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:username)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def sessions
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom


  def create #under show.html.erb, create message by action (ENTER or send)
    message = @chatroom.messages#.new(message_params)
    message.body = params[:body]
    message.user = current_user

    message.save
    redirect_to @chatroom
  end

  private
    def set_chatroom
      @chatroom = Chatroom.find(params[:chatroom_id])
    end

    # def message_params
    #   params.require(:message).permit(:body)
    # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/chatrooms/_form.html.erb
<%= form_with(model: chatroom, local: true) do |form| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
      <% chatroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :chatroom_username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chatrooms</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= chatroom.username %></td>
        <td><%= link_to 'Show', chatroom %></td>
        <td><%= link_to 'Edit', edit_chatroom_path(chatroom) %></td>
        <td><%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chatroom', new_chatroom_path %>

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @chatroom.username %>
</p>

<%= link_to 'Edit', edit_chatroom_path(@chatroom) %> |
<%= link_to 'Back', chatrooms_path %>

app/views/home/sessions.html.erb
<section id="home">
			<div data-velocity="-.3" class="home-parallax"></div>
			<div class="home-overlay"></div>

		<div style="width:100%">
		  	<nav class="navbar navbar-inverse bg-inverse" role="navigation">
		    <div class="navbar-header">
				<a class="navbar-brand" href="index.html">Coinciders</a>
			</div>


		        <ul class="nav navbar-nav navbar-right" style="margin-right:25px">
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><a href="#">Settings</a></li>
		            <li><a href="#">Action</a></li>
		            <li><a href="#">Action</a></li>
		            <li class="divider"></li>
		            <li><a href="#">Logout</a></li>
		          </ul>

		  	</nav>
			</div>

				<table>
				<tr>
					<td colspan="8"><!-- TradingView Widget BEGIN -->
					<script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
					<script type="text/javascript">
					new TradingView.widget({
					  "width": 1100,
					  "height": 775,
					  "symbol": "BITFINEX:BTCUSD",
					  "interval": "D",
					  "timezone": "Australia/Sydney",
					  "theme": "White",
					  "style": "1",
					  "locale": "en",
					  "toolbar_bg": "#f1f3f6",
					  "enable_publishing": false,
					  "allow_symbol_change": true,
					  "withdateranges": true,
					  "hideideas": true
					});
					</script>
					<!-- TradingView Widget END -->
					</td>
					<td></td>

				</table>
		</section>

	<!--scripts and plugins -->
        <!--must need plugin jquery-->
        <script src="js/jquery.min.js"></script>
        <!--bootstrap js plugin-->
        <script src="includes/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

		<!--easying scroll effect-->
		<script src="js/jquery.easing.1.3.min.js" type="text/javascript"></script>
		<script src="js/jquery.sticky.js" type="text/javascript"></script>
		<script src="js/jquery.nav.js" type="text/javascript"></script>
		<!--owl carousel-->
		<script src="includes/owl-carousel/owl.carousel.min.js" type="text/javascript"></script>
		<!--wow animation-->
		<script src="includes/wow-js/wow.min.js" type="text/javascript"></script>

		<!--Activating WOW Animation only for modern browser-->
		<!--[if !IE]><!-->
			<script type="text/javascript">new WOW().init();</script>
		<!--<![endif]-->

		<!--Oh Yes, IE 9+ Supports animation, lets activate for IE 9+-->
		<!--[if gte IE 9]>
			<script type="text/javascript">new WOW().init();</script>
		<![endif]-->

		<!--Opacity & Other IE fix for older browser-->
		<!--[if lte IE 8]>
			<script type="text/javascript" src="js/ie-opacity-polyfill.js"></script>
		<![endif]-->


		<!--parallax-->
		<script src="js/jquery.scrolly.js" type="text/javascript"></script>
		<!--portfolio-filter-->
		<script src="js/isotope.pkgd.min.js" type="text/javascript"></script>
		<!--lightbox-->
		<script src="includes/litebox/images-loaded.min.js" type="text/javascript"></script>
		<script src="includes/litebox/litebox.min.js" type="text/javascript"></script>
		<!--project count-->
		<script src="http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
		<script src="js/jquery.counterup.min.js" type="text/javascript"></script>
		<!--custom scrollbar-->
		<script src="js/jquery.nicescroll.min.js" type="text/javascript"></script>
		<!--Contact Form-->
		<script src="includes/contact-form/app.js" type="text/javascript"></script>
		<script src="includes/contact-form/validatr.js" type="text/javascript"></script>

		<!--customizable plugin edit according to your needs-->
		<script src="js/custom.js" type="text/javascript"></script>




    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Coinciders</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="Perfect Point Marketing">
    <meta name="viewport" content="width=device-width, initial-scale=1">

      <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/themes/smoothness/jquery-ui.css">
      <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

        <!-- Color Pickr -->
        <link href="includes/color-pickr/color-pickr.css" rel="stylesheet">
        <!-- Bootstrap -->
        <link href="includes/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- WOW JS Animation -->
    <link rel="stylesheet" href="includes/wow-js/animations.css" />
    <!-- Litebox  -->
    <link rel="stylesheet" href="includes/litebox/litebox.css" />
    <!-- Owl Carousel -->
    <link rel="stylesheet" href="includes/owl-carousel/owl.carousel.css" />
        <!-- custom css -->
        <link href="stylesheets/application.scss" rel="stylesheet" type="text/css" media="screen">
        <!-- font awesome for icons -->
        <link href="includes/font-awesome-4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Web Fonts -->
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
    <!-- Favicons -->
    <link rel="apple-touch-icon-precomposed" href="/apple-touch-icon-precomposed.png">
    <link rel="icon" href="/favicon.ico">

    <!--[if lte IE 8]>
      <link rel="stylesheet" type="text/css" href="css/fucking-ie-8-and-lower.css" />
    <![endif]-->



    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>
<body onload="init()" id="body">

<div id="preloader">
  <div class="spinner">
    <div class="cube"></div>
    <div class="cube"></div>
    <div class="cube"></div>
    <div class="cube"></div>
    <div class="cube"></div>
    <div class="cube"></div>
    <div class="cube"></div>
    <div class="cube"></div>
    <div class="cube"></div>
  </div>
</div><!--preloader end-->

    <%= yield %>

    <!--scripts and plugins -->
    <!--must need plugin jquery-->
    <script src="javascript/jquery.min.js"></script>
    <!--bootstrap js plugin-->
    <script src="includes/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

    <!--parallax-->
    <script src="javascript/jquery.scrolly.js" type="text/javascript"></script>
    <!--portfolio-filter-->
    <script src="javascript/isotope.pkgd.min.js" type="text/javascript"></script>
    <!--lightbox-->
    <script src="includes/litebox/images-loaded.min.js" type="text/javascript"></script>
    <script src="includes/litebox/litebox.min.js" type="text/javascript"></script>
    <!--project count-->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
    <script src="javascript/jquery.counterup.min.js" type="text/javascript"></script>
    <!--custom scrollbar-->
    <script src="javascript/jquery.nicescroll.min.js" type="text/javascript"></script>
    <!--Contact Form-->
    <script src="includes/contact-form/app.js" type="text/javascript"></script>
    <script src="includes/contact-form/validatr.js" type="text/javascript"></script>

    <!--customizable plugin edit according to your needs-->
    <script src="javascript/custom.js" type="text/javascript"></script>
  </body>
</html>